### PR TITLE
Jp2016102402

### PR DESCRIPTION
**Pull request by HirokazuNishi**
Hi,
I added country specific class mapping for JP. Of course it can use for other countries.
How about these codes?

### CODE REVIEW

**Comment by danielneu** [comment]
Thanks again for the contribution.

**Comment by danielneu** [comment]
Reviewed this PR and I think it can be merged in this sate.
@islandskater43 could you do a sanity review as well?

**Comment by islandskater43** [comment]
First, thank you @HirokazuNishi for submitting these changes! My sincere apologies for the delay in reviewing! They look good to me.

**Comment by danielneu** [comment]
Sent this PR for review to our agency to do a last sanity check.

Thanks for providing this.

**Comment by danielneu** [comment]
Thanks a lot for providing this PR and all the patience.

**Pull request merged**
